/*
  What this file does:
  Provides a curated local-only static password source pack for common and default credentials.

  Why it exists:
  SafePrompt Guard needs a small offline baseline for common/default passwords without relying on
  large breach corpora or live API calls.

  How to extend it:
  Add or remove entries in the curated arrays below, keeping the list intentionally compact and
  high-confidence to avoid false positives and extension bloat.
*/

(function attachSafePromptPasswordSources(global) {
  const source = {
    commonPasswords: [
      // Numeric only
      "123456",
      "12345678",
      "123456789",
      "1234567890",
      "111111",
      "000000",
      "112233",
      "123123",
      // Alphabet + number combos
      "abc123",
      "abc1234",
      "pass1234",
      "pass12345",
      "pass123",
      // admin / default words
      "admin123",
      "admin1234",
      "admin2024",
      "admin2025",
      "Admin123",
      "Admin2024",
      "changeme",
      "changeme123",
      "ChangeMe123",
      "default",
      "Default123",
      "letmein",
      "letmein123",
      // Password variants
      "password",
      "password1",
      "password12",
      "password2024",
      "password2025",
      "Password1",
      "Password1!",
      "Password12",
      "Password123",
      "Password123!",
      "Password2024",
      "Password2025",
      "Passw0rd",
      "Passw0rd!",
      "P@ssw0rd",
      "P@ssword1",
      "P@ssword123",
      // Welcome variants
      "Welcome1",
      "Welcome1!",
      "Welcome123",
      "Welcome123!",
      "Welcome2023",
      "Welcome2024",
      "Welcome2025",
      // Temp / initial
      "TempPass123",
      "TempPass123!",
      "Temp1234",
      "Initial1",
      "Initial123",
      "InitialPass1",
      // Qwerty / keyboard walks
      "Qwerty123",
      "Qwerty123!",
      "qwerty123",
      "1qaz2wsx",
      "1Qaz2Wsx",
      "!QAZ2wsx",
      "zaq1xsw2",
      // Seasonal patterns
      "Summer2023",
      "Summer2024",
      "Summer2025",
      "Winter2023",
      "Winter2024",
      "Winter2025",
      "Spring2024",
      "Spring2025",
      "Autumn2024",
      "Fall2024",
      "Fall2025",
      // Month-year combos
      "January2024",
      "February2024",
      "March2024",
      "April2024",
      "May2024",
      "June2024",
      "July2024",
      "August2024",
      "September2024",
      "October2024",
      "November2024",
      "December2024",
      "January2025",
      "June2025",
      // Corporate one-time / rotate patterns
      "Monday123",
      "Sunday123",
      "Company123",
      "Company2024",
      "Corp2024",
      "Office2024",
      "Service123",
      "Service2024",
      "Login2024",
      "Login123",
      "Start123",
      "Start2024",
      "Rotate123",
      "Reset2024",
      "Onboard1",
      "Onboard123",
      // Common substitution patterns
      "Welc0me1",
      "Welc0me123",
      "4dm1n",
      "4dm1n123",
      "s3cret",
      "S3cret123",
      "s3cur3",
      "S3curity1",
      // Short memorable
      "monkey1",
      "dragon1",
      "master1",
      "sunshine1",
      "letme1n",
      "iloveyou1",
      "secret123",
      "Secret123"
    ],
    defaultPasswords: [
      "admin",
      "administrator",
      "cisco",
      "default",
      "guest",
      "manager",
      "oracle",
      "password",
      "password1",
      "public",
      "root",
      "support",
      "system",
      "toor",
      "user",
      "pass",
      "1234",
      "12345",
      "test",
      "test123",
      "blank",
      "alpine",
      "ubnt",
      "service",
      "changeme",
      "letmein",
      "master",
      "secret",
      "welcome",
      "devops",
      "deploy"
    ],
    defaultCredentialPairs: [
      { username: "admin", password: "admin" },
      { username: "admin", password: "password" },
      { username: "admin", password: "123456" },
      { username: "admin", password: "1234" },
      { username: "admin", password: "changeme" },
      { username: "admin", password: "letmein" },
      { username: "administrator", password: "administrator" },
      { username: "administrator", password: "password" },
      { username: "cisco", password: "cisco" },
      { username: "guest", password: "guest" },
      { username: "guest", password: "" },
      { username: "manager", password: "manager" },
      { username: "oracle", password: "oracle" },
      { username: "root", password: "root" },
      { username: "root", password: "toor" },
      { username: "root", password: "password" },
      { username: "root", password: "alpine" },
      { username: "root", password: "ubnt" },
      { username: "sa", password: "sa" },
      { username: "sa", password: "" },
      { username: "support", password: "support" },
      { username: "user", password: "user" },
      { username: "user", password: "password" },
      { username: "test", password: "test" },
      { username: "test", password: "test123" },
      { username: "deploy", password: "deploy" },
      { username: "service", password: "service" },
      { username: "devops", password: "devops" },
      { username: "pi", password: "raspberry" },
      { username: "ubnt", password: "ubnt" }
    ],
    metadata: {
      posture: "local-first-static-bundle",
      curatedFrom: [
        "SecLists Common-Credentials",
        "SecLists Default-Credentials",
        "CIRT Default Password Database"
      ],
      notes: "Expanded curated set for v2. Covers seasonal patterns, corporate one-time passwords, default credentials, and keyboard walks. Full breach corpora and live APIs are intentionally excluded."
    }
  };

  global.SafePromptPasswordSources = source;
})(globalThis);
